# Generated by Django 5.0 on 2025-10-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
