# Generated by Django 5.0 on 2025-09-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_tasks',
            field=models.TextField(blank=True, help_text='Comma-separated list of weekly tasks'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('worker', 'Worker'), ('farm_worker', 'Farm Worker'), ('farm_accountant', 'Farm Accountant'), ('guest', 'Guest User')], default='guest', max_length=20),
        ),
    ]
