# Generated by Django 5.0 on 2025-08-13 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('breed', models.CharField(choices=[('Jersey', 'Jersey'), ('Holstein', 'Holstein'), ('Guernsey', 'Guernsey'), ('Ayrshire', 'Ayrshire'), ('Brown_Swiss', 'Brown Swiss'), ('Zebu', 'Zebu'), ('Crossbreed', 'Crossbreed')], max_length=20)),
                ('year_of_birth', models.IntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True)),
                ('health_status', models.CharField(blank=True, default='Healthy', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_father', to='animals.animal')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_mother', to='animals.animal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
