# Generated by Django 5.0 on 2025-09-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Goat', 'Goat'), ('Sheep', 'Sheep'), ('Pig', 'Pig'), ('Dog', 'Dog')], default='Cow', max_length=10),
        ),
    ]
